name: stripe
version: 0.0.1
authors:
  - Matias Meno <m@tias.me>
  - Martin Flucka <martin.flucka@gmail.com>
description: Stripe API wrapper
homepage: https://github.com/exitlive/stripe-dart
documentation: https://github.com/exitlive/stripe-dart
dependencies:
  http: ">=0.9.0"
  logging: ">=0.9.0"
dev_dependencies:
  unittest: any
