name: stripe
version: 1.1.0
authors:
  - Matias Meno <m@tias.me>
  - Martin Flucka <martin.flucka@gmail.com>
description: Stripe API wrapper
homepage: git@github.com:exitlive/stripe-dart.git
documentation: git@github.com:exitlive/stripe-dart.git
dependencies:
  http: ">=0.9.0 <0.10.0"
  logging: ">=0.9.0 <0.10.0"
dev_dependencies:
  unittest: ">=0.11.0 <0.12.0"
